[tasks.run-dev]
command = "zola"
args = ["serve"]

[tasks.run-release]
command = "zola"
args = ["build"]

[tasks.update-pages]
command = "git"
args = ["subtree", "push", "--prefix", "public", "origin", "gh-pages"]
